CREATE SEQUENCE SEQ_MEMBER3_NO
	START WITH 1
	INCREMENT BY 1
	NOMINVALUE
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
    
CREATE SEQUENCE SEQ_STUDENT3_NO
	START WITH 1
	INCREMENT BY 1
	NOMINVALUE
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
    
CREATE SEQUENCE SEQ_TEACHERS3_NO
	START WITH 1
	INCREMENT BY 1
	NOMINVALUE
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
    
CREATE SEQUENCE SEQ_COURSE3_NO
	START WITH 1
	INCREMENT BY 1
	NOMINVALUE
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
    
CREATE SEQUENCE SEQ_LECTURE3_NO
	START WITH 1
	INCREMENT BY 1
	NOMINVALUE
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
    
CREATE SEQUENCE SEQ_VIDEO3_NO
	START WITH 1
	INCREMENT BY 1
	NOMINVALUE
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
    
CREATE SEQUENCE SEQ_MEMBER_LECTURE3_NO
	START WITH 1
	INCREMENT BY 1
	NOMINVALUE
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
    
CREATE SEQUENCE SEQ_COURSE_REGISTER3_NO
	START WITH 1
	INCREMENT BY 1
	NOMINVALUE
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
    
CREATE SEQUENCE SEQ_COURSE_CATEGORY3_NO
	START WITH 1
	INCREMENT BY 1
	NOMINVALUE
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
    
CREATE SEQUENCE SEQ_CART3_NO
	START WITH 1
	INCREMENT BY 1
	NOMINVALUE
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
    
CREATE SEQUENCE SEQ_POST3_NO
	START WITH 1
	INCREMENT BY 1
	NOMINVALUE
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
    
CREATE SEQUENCE SEQ_BOARD_CATEGORY3_NO
	START WITH 1
	INCREMENT BY 1
	NOMINVALUE
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
    
CREATE SEQUENCE SEQ_FILE3_NO
	START WITH 1
	INCREMENT BY 1
	NOMINVALUE
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
    
CREATE SEQUENCE SEQ_COMMENT3_NO
	START WITH 1
	INCREMENT BY 1
	NOMINVALUE
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
    
CREATE SEQUENCE SEQ_IMAGE3_NO
	START WITH 1
	INCREMENT BY 1
	NOMINVALUE
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
    
CREATE SEQUENCE SEQ_LIKE3_NO
	START WITH 1
	INCREMENT BY 1
	NOMINVALUE
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
    
CREATE SEQUENCE SEQ_PAYMENTS3_NO
	START WITH 1
	INCREMENT BY 1
	NOMINVALUE
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
    
CREATE SEQUENCE SEQ_BOOK3_NO
	START WITH 1
	INCREMENT BY 1
	NOMINVALUE
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
    
CREATE SEQUENCE SEQ_PAYMENT_CANCELLATIONS3_NO
	START WITH 1
	INCREMENT BY 1
	NOMINVALUE
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
    
CREATE SEQUENCE SEQ_PAYMENT_STATUS_HISTORY3_NO
	START WITH 1
	INCREMENT BY 1
	NOMINVALUE
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
    
CREATE SEQUENCE SEQ_SCHEDULE_EVENT3_NO
	START WITH 1
	INCREMENT BY 1
	NOMINVALUE
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
   
CREATE SEQUENCE SEQ_SUBJECT3_NO
	START WITH 1
	INCREMENT BY 1
	NOMINVALUE
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
COMMIT;
    
--3주차 시퀀스 목록
--SEQ_MEMBER3_NO
--SEQ_STUDENT3_NO
--SEQ_TEACHERS3_NO
--SEQ_COURSE3_NO
--SEQ_LECTURE3_NO
--SEQ_VIDEO3_NO
--SEQ_MEMBER_LECTURE3_NO
--SEQ_COURSE_REGISTER3_NO
--SEQ_COURSE_CATEGORY3_NO
--SEQ_CART3_NO
--SEQ_POST3_NO
--SEQ_BOARD_CATEGORY3_NO
--SEQ_FILE3_NO
--SEQ_COMMENT3_NO
--SEQ_IMAGE3_NO
--SEQ_LIKE3_NO
--SEQ_PAYMENTS3_NO
--SEQ_BOOK3_NO
--SEQ_PAYMENT_CANCELLATIONS3_NO
--SEQ_PAYMENT_STATUS_HISTORY3_NO
--SEQ_SCHEDULE_EVENT3_NO
--SEQ_SUBJECT3_NO